<<<<<<< HEAD
# Generated by Django 3.2.13 on 2022-11-24 01:25
=======
# Generated by Django 3.2.13 on 2022-11-24 02:16
>>>>>>> 756566467b767f7488b9a1f0a4571faa7984ac26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('auth', '0012_alter_user_first_name_max_length'),
        ('movies', '0001_initial'),
        ('accounts', '0001_initial'),
=======
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('movies', '0001_initial'),
>>>>>>> 756566467b767f7488b9a1f0a4571faa7984ac26
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prefer_movies',
            field=models.ManyToManyField(related_name='prefer_users', to='movies.Movie'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
