<<<<<<< HEAD
# Generated by Django 3.2.13 on 2022-11-18 00:58
=======
# Generated by Django 3.2.13 on 2022-11-18 00:40
>>>>>>> 37c6f6de0ed7836744825198c72d5472e6c15992

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('movies', '0001_initial'),
        ('accounts', '0001_initial'),
=======
        ('accounts', '0001_initial'),
        ('movies', '0001_initial'),
>>>>>>> 37c6f6de0ed7836744825198c72d5472e6c15992
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prefer_movies',
            field=models.ManyToManyField(related_name='prefer_users', to='movies.Movie'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
